# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87293a1140cfc12107fba474e3cb4f7d248afc0637b70a7febc72f6e7707a41ecfa6eb10dd21f6d8c970923f36e3df9217dc3f96ce978d3451d146f99fa20e09

test:
  secret_key_base: 540332ea0d8c1b5e646ae1c6c91c3d623bb9129625ee479eaf3a000c6db260bc71b05840e65624bd3582292feed51218eeca4bb2d29ce872c5ee9c397a734004

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
